import React from 'react';
import { AppWindow, Archive, ArrowRight, Flag, LayoutDashboard, PanelsTopLeft, Star, Users } from 'lucide-react';
import { useApp } from '../../context/AppContext';

const pageDetails = {
  plans: ['Plans', 'Plan management is coming to SprintFlow. Your current projects and work items remain available in the meantime.', Flag],
  assets: ['Assets', 'Asset management is coming to SprintFlow. This space is ready for shared project resources.', Archive],
  goals: ['Goals', 'Goal tracking is coming to SprintFlow. Use the roadmap to keep current milestones visible.', Flag],
};

export function WorkspacePage() {
  const { workspacePage, recentPages, userSpaces, orgs, starredOrgIds, toggleStarredOrg, selectOrg, setTeamTab, setViewMode, allTasks, navigateTo } = useApp();
  const activeSpaces = userSpaces || orgs;
  const goToOrg = (orgId, tab = 'board') => { selectOrg(orgId); setTeamTab(tab); };
  if (pageDetails[workspacePage]) { const [title, body, Icon] = pageDetails[workspacePage]; return <Placeholder title={title} body={body} icon={Icon} />; }
  if (workspacePage === 'recent') return <PageShell title="Recent" subtitle="Pick up where you left off."><div className="space-y-2">{recentPages.filter((page) => page !== 'recent').map((page) => <button key={page} onClick={() => navigateTo(page)} className="flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3 text-left text-sm font-semibold text-slate-700 hover:border-blue-300 hover:text-[#0052cc]"><span className="capitalize">{page === 'personal' ? 'For you' : page}</span><ArrowRight className="h-4 w-4" /></button>)}</div></PageShell>;
  if (workspacePage === 'starred') return <PageShell title="Starred" subtitle="Spaces you have pinned for faster access."><ProjectList orgs={activeSpaces.filter((org) => starredOrgIds.includes(org.id))} onOpen={goToOrg} onStar={toggleStarredOrg} starredOrgIds={starredOrgIds} empty="Star spaces from the Spaces list to see them here." /></PageShell>;
  if (workspacePage === 'teams' || workspacePage === 'spaces') return <PageShell title="Spaces" subtitle="Your accessible SprintFlow spaces and workspaces."><ProjectList orgs={activeSpaces} onOpen={goToOrg} onStar={toggleStarredOrg} starredOrgIds={starredOrgIds} /></PageShell>;
  if (workspacePage === 'apps') return <PageShell title="Apps" subtitle="Open the collaboration tools already available in this workspace."><div className="grid gap-3 sm:grid-cols-2">{[{ label: 'Kanban board', tab: 'board', icon: LayoutDashboard }, { label: 'Roadmap', tab: 'roadmap', icon: Flag }, { label: 'Whiteboard', tab: 'canvas', icon: AppWindow }, { label: 'Team chat', tab: 'chat', icon: Users }].map(({ label, tab, icon: Icon }) => <button key={tab} onClick={() => { setViewMode('team'); setTeamTab(tab); navigateTo('apps'); }} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 text-left text-sm font-bold text-slate-700 transition-colors hover:border-blue-300 hover:bg-blue-50 hover:text-[#0052cc]"><Icon className="h-5 w-5" />{label}</button>)}</div></PageShell>;
  if (workspacePage === 'filters') return <PageShell title="Filters" subtitle="A live view of your actual work items."><div className="space-y-2">{allTasks.slice(0, 8).map((task) => <button onClick={() => goToOrg(task.orgId)} key={task.id} className="flex w-full items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3 text-left hover:border-blue-300"><span><span className="mr-2 font-mono text-xs font-bold text-[#0052cc]">{task.key}</span><span className="text-sm font-semibold text-slate-700">{task.title}</span></span><span className="text-xs text-slate-400">{task.status.replace('_', ' ')}</span></button>)}</div></PageShell>;
  return <Placeholder title="Workspace" body="Choose an item in the sidebar to continue." icon={PanelsTopLeft} />;
}

function PageShell({ title, subtitle, children }) { return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="mb-6"><h1 className="text-2xl font-extrabold tracking-tight text-[#172b4d]">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{children}</div>; }
function Placeholder({ title, body, icon: Icon }) { return <PageShell title={title} subtitle="SprintFlow workspace"><div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><Icon className="mx-auto h-8 w-8 text-[#0052cc]" /><h2 className="mt-3 text-sm font-bold text-slate-700">{title}</h2><p className="mx-auto mt-1 max-w-md text-xs leading-relaxed text-slate-500">{body}</p></div></PageShell>; }
function ProjectList({ orgs, onOpen, onStar, starredOrgIds, empty }) { if (!orgs.length) return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">{empty}</div>; return <div className="grid gap-3 sm:grid-cols-2">{orgs.map((org) => { const starred = starredOrgIds.includes(org.id); return <div key={org.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-2"><div><h2 className="text-sm font-bold text-[#172b4d]">{org.name}</h2><p className="mt-1 text-xs text-slate-500">{org.description}</p></div><button onClick={() => onStar(org.id)} aria-label={`${starred ? 'Unstar' : 'Star'} ${org.name}`} className={`rounded-lg p-1.5 ${starred ? 'text-amber-500' : 'text-slate-400 hover:text-amber-500'}`}><Star className="h-4 w-4" fill={starred ? 'currentColor' : 'none'} /></button></div><button onClick={() => onOpen(org.id)} className="mt-4 text-xs font-bold text-[#0052cc] hover:text-[#0041a8]">Open project <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></button></div>; })}</div>; }
